name: mmic
channels:

  - defaults
  - conda-forge
  - bioconda

dependencies:
    # Base depends
  - python=3.9.0
  - pip
  - autodock-vina
  - openbabel
  - nwchem

    # Testing
  - pytest
  - pytest-cov

  # Pip-only installs
  - pip:
    - networkx
    - codecov
    - qcelemental
    - pydantic
    - git+https://github.com/andrew-abimansour/qcengine.git@execute
    - git+https://github.com/molssi/cmselemental.git@dev
    - git+https://github.com/parmed/parmed.git
    - git+https://github.com/MolSSI/mmic.git
    - git+https://github.com/MolSSI/mmelemental.git
    - git+https://github.com/MolSSI/mmic_translator.git
    - git+https://github.com/MolSSI/mmic_parmed.git
    - git+https://github.com/MolSSI/mmic_qcschema.git
    - git+https://github.com/MolSSI/mmic_docking.git
    - git+https://github.com/MolSSI/mmic_autodock_vina.git
    - git+https://github.com/MolSSI/mmic_cmd.git
    - git+https://github.com/MolSSI/mm_data.git
    - git+https://github.com/andrew-abimansour/nglview.git
